const ECategory = {
  FOODITEMS: { value: 'FOODITEMS', displayName: 'Food items' },
  BEVERAGES: { value: 'BEVERAGES', displayName: 'Beverages' },
  CLOTHING: { value: 'CLOTHING', displayName: 'Clothing' },
  TOOLS: { value: 'TOOLS', displayName: 'Tools' },
  WEAPONS: { value: 'WEAPONS', displayName: 'Weapons' },
  ELECTRONICS: { value: 'ELECTRONICS', displayName: 'Electronics' },
  HOMEAPPLIANCES: { value: 'HOMEAPPLIANCES', displayName: 'Home appliances' },
  JEWELRY: { value: 'JEWELRY', displayName: 'Jewelry' },
  BEAUTYPRODUCTS: { value: 'BEAUTYPRODUCTS', displayName: 'Beauty products' },
  ARTSUPPLIES: { value: 'ARTSUPPLIES', displayName: 'Art supplies' },
  SPORTSEQUIPMENT: { value: 'SPORTSEQUIPMENT', displayName: 'Sports equipment' },
  MUSICALINSTRUMENTS: { value: 'MUSICALINSTRUMENTS', displayName: 'Musical instruments' },
  BOOKS: { value: 'BOOKS', displayName: 'Books' },
  TOYSANDGAMES: { value: 'TOYSANDGAMES', displayName: 'Toys and games' },
  OFFICESUPPLIES: { value: 'OFFICESUPPLIES', displayName: 'Office supplies' },
  AUTOMOTIVESUPPLIES: { value: 'AUTOMOTIVESUPPLIES', displayName: 'Automotive supplies' },
  CLEANINGSUPPLIES: { value: 'CLEANINGSUPPLIES', displayName: 'Cleaning supplies' },
  HEALTHANDWELLNESSPRODUCTS: { value: 'HEALTHANDWELLNESSPRODUCTS', displayName: 'Health and wellness products' },
  GARDENINGTOOLS: { value: 'GARDENINGTOOLS', displayName: 'Gardening tools' },
  PETSUPPLIES: { value: 'PETSUPPLIES', displayName: 'Pet supplies' },
  TRAVELACCESSORIES: { value: 'TRAVELACCESSORIES', displayName: 'Travel accessories' },
  HOMEDECOR: { value: 'HOMEDECOR', displayName: 'Home decor' },
  STATIONERY: { value: 'STATIONERY', displayName: 'Stationery' },
  DIYSUPPLIES: { value: 'DIYSUPPLIES', displayName: 'DIY supplies' },
  CAMPINGGEAR: { value: 'CAMPINGGEAR', displayName: 'Camping gear' },
  FISHINGEQUIPMENT: { value: 'FISHINGEQUIPMENT', displayName: 'Fishing equipment' },
  HUNTINGGEAR: { value: 'HUNTINGGEAR', displayName: 'Hunting gear' },
  EXERCISEEQUIPMENT: { value: 'EXERCISEEQUIPMENT', displayName: 'Exercise equipment' },
  PARTYSUPPLIES: { value: 'PARTYSUPPLIES', displayName: 'Party supplies' },
  EDUCATIONALMATERIALS: { value: 'EDUCATIONALMATERIALS', displayName: 'Educational materials' }
};
export default ECategory;